name: flutter_thai_hotline_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.1
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  carousel_slider: ^5.1.2
  introduction_screen: ^3.1.12

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/intro.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/sub_a/
    - assets/images/sub_b/
    - assets/images/sub_c/
    - assets/images/sub_d/

